version: "3"
services:
  tinc:
    image: snadn/tinc
    devices:
      - "/dev/net/tun"
    network_mode: "host"
    cap_add:
      - "NET_ADMIN"
    volumes:
      - "./tinc:/etc/tinc"
    restart: always
